### ISSUE TITLE
Asserion error on running `python setup.py install`

### ISSUE THREAD

**Issue by lken01** [uoip/pangolin#20]
Hi,
I am getting this error on running `python setup.py install`

```
running install
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    graphical data."""
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 22, in run
    assert len(lib_file) == 1 and len(install_dirs) >= 1     
AssertionError
```

**Comment by lken01** [comment]
I found the solution. The `setup.py` had a correction to be made. The variable `install_dirs` has been initialized as `install_dir`.

**Comment by ZisisT** [comment]
I tried that but im still getting the same error, any ideas?

**Comment by KunB-Fighting** [comment]
you can just copy the .so file to your python lib path, or you can add
`install_dirs = [install_dir] `
to initialize install_dirs as a list.

**Comment by solbach** [comment]
> you can just copy the .so file to your python lib path, or you can add
> `install_dirs = [install_dir] `
> to initialize install_dirs as a list.

I was also struggling with this. @LeemeetElaine is completly right. Changing the code to this worked:

```
def run(self):
        install_dir = get_python_lib()
        install_dirs = [install_dir]

        lib_file = glob.glob(__library_file__)
        assert len(lib_file) == 1 and len(install_dirs) >= 1     

        print('copying {} -> {}'.format(lib_file[0], install_dirs[0]))
        shutil.copy(lib_file[0], install_dir)
```
Then running:
```sudo python3.6 setup.py install```
If you need sudo rights, e.g. dir is _/usr/lib/..._
No sudo is required for most install dir locations when using virtual environments etc.

**Comment by zhufeng888** [comment]
I add install_dirs = [install_dir] but it still put the same error "AssertionError", I have struggled with pangolin in python for a day, tired.

**Comment by fsan** [comment]
@KunB-Fighting solution worked for me

just after install_dirs definition after install_dir

```python3
    def run(self):
        install_dir = get_python_lib()
        install_dirs = [install_dir]
```

running `python setup.py install` will copy the so file to my conda environment and then I used the demo application from the readme

note: I installed stevenlovegrove main pangolin before. I had a problem while building due to something missing dependency of eigen library but it was actually missing a dependecy for eigen3-devel in my system and it was not listed in the cmake

**Comment by harshitsinghcode** [comment]
same error !!

![image](https://github.com/uoip/pangolin/assets/110082422/bd74c6eb-848f-4c18-88e5-b63ae9731c39)

**Comment by harshitsinghcode** [comment]
@fsan @solbach

**Comment by fsan** [comment]
not sure what you need @harshitsinghcode, but you should probably look into the[ main fork](https://github.com/stevenlovegrove/Pangolin) and/or then try to contact the authors. Last commit on this fork is like 7 years old already.
If the problem persists there, then you can collaborate with a patch to fix the problem

**Comment by harshitsinghcode** [comment]
I mentioned you because u also had the same error!

**Comment by yishaiSilver** [comment]
I had this error because the build failed. I think it was trying to link the wrong python. 

```cmake .. -DPython_EXECUTABLE=`which python3` -DBUILD_PANGOLIN_FFMPEG=OFF```

Worked for me on python 3.10

**Comment by Brilliant-Pig** [comment]
> I add install_dirs = [install_dir] but it still put the same error "AssertionError", I have struggled with pangolin in python for a day, tired.

So, has this error been solved?

**Comment by harshitsinghcode** [comment]
> > I add install_dirs = [install_dir] but it still put the same error "AssertionError", I have struggled with pangolin in python for a day, tired.
> 
> So, has this error been solved?

yup!!
