### ISSUE TITLE
Can anyone compile this?

### ISSUE THREAD

**Issue by kevkid** [uoip/pangolin#33]
Ubuntu 20.04, I can't compile this at all.

**Comment by kevkid** [comment]
Okay I got it compiled I was getting this error:
```
make[2]: *** [src/CMakeFiles/_pangolin.dir/build.make:999: src/CMakeFiles/_pangolin.dir/video/drivers/ffmpeg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:516: src/CMakeFiles/_pangolin.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
to solve we just so `cmake -DBUILD_PANGOLIN_FFMPEG=OFF ..`

Also if you get something like this: 

```
pangolin/include/pangolin/display/opengl_render_state.h:40:10: fatal error: Eigen/Core: No such file or directory
   40 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~

```
I just installed: `sudo apt install libeigen3-dev`

if you get this error:
```
Traceback (most recent call last):
  File "HelloPangolin.py", line 4, in <module>
    import pangolin
ImportError: /usr/lib/python3/dist-packages/pangolin.so: undefined symbol: _Py_ZeroStruct

```
you must also tell cmake where python is:

`cmake -DBUILD_PANGOLIN_FFMPEG=OFF -DPYBIND11_PYTHON_VERSION=3.8 ..`

NOTE: I did install eigen-3.3.4 from source

**Comment by chopin1998** [comment]
> Okay I got it compiled I was getting this error:
> 
> ```
> make[2]: *** [src/CMakeFiles/_pangolin.dir/build.make:999: src/CMakeFiles/_pangolin.dir/video/drivers/ffmpeg.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:516: src/CMakeFiles/_pangolin.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> ```
> 
> to solve we just so `cmake -DBUILD_PANGOLIN_FFMPEG=OFF ..`
> 
> Also if you get something like this:
> 
> ```
> pangolin/include/pangolin/display/opengl_render_state.h:40:10: fatal error: Eigen/Core: No such file or directory
>    40 | #include <Eigen/Core>
>       |          ^~~~~~~~~~~~
> ```
> 
> I just installed: `sudo apt install libeigen3-dev`
> 
> if you get this error:
> 
> ```
> Traceback (most recent call last):
>   File "HelloPangolin.py", line 4, in <module>
>     import pangolin
> ImportError: /usr/lib/python3/dist-packages/pangolin.so: undefined symbol: _Py_ZeroStruct
> ```
> 
> you must also tell cmake where python is:
> 
> `cmake -DBUILD_PANGOLIN_FFMPEG=OFF -DPYBIND11_PYTHON_VERSION=3.8 ..`
> 
> NOTE: I did install eigen-3.3.4 from source

also ubuntu 20.04

follow your method, compile fine, but make install error:

```
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/home/marco/tmp/build/pangolin/build/src/include/_pangolin/config.h": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:43 (include)


make: *** [Makefile:108: install] Error 1
```

did you meet this?

**Comment by scimad** [comment]
This is fixed by PR #30.

**Comment by PAPPY-JOE** [comment]
I can't get around this please, and I have tried everything here

`/home/bu22mct2004/pangolin/src/image/image_io_jpg.cpp: In function ‘pangolin::TypedImage pangolin:
LoadJpg(std::istream&)’:
/home/bu22mct2004/pangolin/src/image/image_io_jpg.cpp:180:13: error: ‘uint8_t’ was not declared in this scope
  180 |             uint8_t* dstRow = (uint8_t*)image.RowPtr(y);
      |             ^~~~~~~
/home/bu22mct2004/pangolin/src/image/image_io_jpg.cpp:11:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   10 | #  include <jpeglib.h>
  +++ |+#include <cstdint>
   11 | #  ifdef _WIN_
/home/bu22mct2004/pangolin/src/image/image_io_jpg.cpp:180:22: error: ‘dstRow’ was not declared in this scope
  180 |             uint8_t* dstRow = (uint8_t*)image.RowPtr(y);
      |                      ^~~~~~
/home/bu22mct2004/pangolin/src/image/image_io_jpg.cpp:180:40: error: expected primary-expression before ‘)’ token
  180 |             uint8_t* dstRow = (uint8_t*)image.RowPtr(y);
      |                                        ^
make[2]: *** [src/CMakeFiles/_pangolin.dir/build.make:188: src/CMakeFiles/_pangolin.dir/image/image_io_jpg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:462: src/CMakeFiles/_pangolin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2`
